### ISSUE TITLE
openwrt package

### ISSUE THREAD

**Issue by EnzoGehlen** [BroadbandForum/obuspa#107]
is there any way to embed obuspa into openwrt? i've look up some articles but there's poor info on the internet about obuspa.

**Comment by peStoney** [comment]
obuspa itself could be easily added to OpenWrt. But obuspa does not implement and data model/telemetry translation from TR-181 to the devices internal data structures (in case of OpenWrt that's uci or since 23.05 alternatively uRender). There are several projects that address this in various ways, but that's out of obuspa's scope.
