### ISSUE TITLE
Value change of "Device.MQTT.{i}.ConnectRetryTime" can't be applied to mqtt

### ISSUE THREAD

**Issue by wildmeng** [BroadbandForum/obuspa#109]
Hi, 
We just found that changing value of the MQTT.{i}.ConnectRetryTime doesn't work for the mqtt connect retry time, has to restart the obuspa to make it effective.

what i found in the code is that the function "NotifyChange_MQTTConnectRetryTime" maybe should call the MQTT_UpdateRetryParams(which was not implemented) to sync the new values to the mqtt.c ?

is this a bug or something TODO in the plan?

thanks!
Xiaofeng Meng

**Comment by holme-r** [comment]
Currently an updated ConnectRetryTime is only applied if OBUSPA is restarted or if there is a Controller initiated reconnect. We've noted this as a bug which is most likely to be an issue when first onboarding a device, changing ConnectRetryTime from it's default. It could result in any subsequent reconnects being at a different frequency than anticipated, until OBUSPA is restarted. It would be unusual to change ConnectRetryTime at any time other than first onboarding a device. Typically this parameter is set up once, then forgotten about.

**Comment by wildmeng** [comment]
thanks for your reply!
exactly, we do that when anboarding a device, are you going to fix this bug or not?
i noticed that the function "MQTT_UpdateRetryParams" could be useful for that, why was the function not implemented?

**Comment by holme-r** [comment]
Yes, to fix this issue, we will probably need to write a function called something like MQTT_UpdateRetryParams (which does not exist in the codebase currently)
This issue is not particularly high priority since it only results in retries being at the wrong frequency after first onboarding a device, and before the device is rebooted. Firstly retries are unlikely, and secondly if they do occur, being at the wrong frequency should not really be an issue - as the MQTT Broker will need to cope with devices retrying at the wrong frequency before they've been onboarded anyway. If it is an issue, then the workaround is for onboarding to issue the USP Reboot() command to the device after setting up the new configuration.

**Comment by holme-r** [comment]
Closing as fixed in OBUSPA v8.0.5
