### ISSUE TITLE
command faild (core dumped)

### ISSUE THREAD

**Issue by ahmedrs1** [BroadbandForum/obuspa#15]
I excute the cli command: obuspa -c show database 
output is:
Running command on database /usr/local/var/obuspa/usp.db
DEVICE_SECURITY_CreateSSLContext: SSL_CTX_new failed
Failed assert at InitClient(1599): client->ssl_ctx != NULL
Exiting USP Agent
Aborted (core dumped)

so please help me out, what i need to do to come out from this error.

**Comment by r-holme** [comment]
The call to SSL_CTX_new() is failing. I don't know why it is failing, but maybe it is because your SSL library does not support the method specified by SSLv23_client_method() ?

**Comment by ahmedrs1** [comment]
OpenSSL version:
OpenSSL 1.0.2g  1 Mar 2016

**Comment by r-holme** [comment]
Thank you. The problem can be fixed in the function DATA_MODEL_Init(), by calling DEVICE_SECURITY_Init() before DEVICE_MQTT_Init(). This issue wasn't spotted earlier because later versions of OpenSSL seem to be more lenient of SSL_CTX_new() being called before SSL_library_init(). This issue will be fixed in the next release of OBUSPA.
