### ISSUE TITLE
Agent crashes when nested objects are created in an ADD message with allow_partial=false

### ISSUE THREAD

**Issue by masponer** [BroadbandForum/obuspa#37]
As discussed in Slack (https://broadband-forum.slack.com/archives/C017V6HCYMN/p1640077274056000) obuspa crashes when it receives the following USP ADD message:
`header {
  msg_id: "64a4c46f-e809-4eea-a2a4-fc1f939574c1"
  msg_type: ADD
}
body {
  request {
    add {
      allow_partial: false
      create_objs {
        obj_path: "Device.LocalAgent.Controller."
        param_settings {
          param: "Enable"
          value: "true"
          required: false
        }
        param_settings {
          param: "Alias"
          value: "cpe-usp-test-controller"
          required: false
        }
        param_settings {
          param: "EndpointID"
          value: "proto::add-controller-test"
          required: false
        }
      }
      create_objs {
        obj_path: "Device.LocalAgent.Controller.[Alias == "cpe-usp-test-controller"].MTP."
        param_settings {
          param: "Enable"
          value: "true"
          required: false
        }
        param_settings {
          param: "Protocol"
          value: "MQTT"
          required: false
        }
      }
    }
  }
}`

The follow error log is written:
`ADD : processing at time 2021-12-21T07:55:39Z
Failed assert at ValidateAdd_ControllerMtp(1057): cont != NULL
Callstack is:-
 main()
  DM_EXEC_Main()
   ProcessMessageQueueSocketActivity()
    ProcessBinaryUspRecord()
     MSG_HANDLER_HandleBinaryRecord()
      MSG_HANDLER_HandleBinaryMessage()
       HandleUspMessage()
        MSG_HANDLER_HandleAdd()
         CreateExpressionObjects()
          CreateObject_Trans()
           CreateObject()
            DATA_MODEL_AddInstance()
             Unknown()
              USP_LOG_Init()
               USP_ERR_Terminate()
Exiting USP Agent
ERROR: Segmentation Fault
Callstack is:-
 main()
  DM_EXEC_Main()
   ProcessMessageQueueSocketActivity()
    ProcessBinaryUspRecord()
     MSG_HANDLER_HandleBinaryRecord()
      MSG_HANDLER_HandleBinaryMessage()
       HandleUspMessage()
        MSG_HANDLER_HandleAdd()
         CreateExpressionObjects()
          CreateObject_Trans()
           CreateObject()
            DATA_MODEL_AddInstance()
             Unknown()
              USP_LOG_Init()
               Unknown()
                abort()
                 Unknown()
                  SegFaultHandler()`

When the same request is made with allow_partial=true, it going through fine and both data model objects are correctly stored in the agent DB.

In my view the agent behaviour is faulty as it shouldn't crash when it receives a single (eventually incorrect) USP message.

**Comment by duttajnu** [comment]
Hi @masponer,

The create_objs syntax used violates USP requirement:

```
R-ADD.2 - The obj_path field in the CreateObject message of an Add Request MUST NOT
contain Search Paths.
```

**Comment by masponer** [comment]
Hi @duttajnu,
valid point, which I wasn't aware of yet.
But wouldn't you agree that an invalid input should not lead an agent crash? In my view the component should be more "robust" in that regard and ignore the input, if it's not valid. Stability is an important factor. If the agent is not running the CPE is not remotely managable anymore, which should be avoided as best as possible.

**Comment by holme-r** [comment]
The agent should not crash, this is a bug. It crashes due to an assumption in the code that the Controller (parent) object must exist in the local data structure because otherwise the path resolver wouldn't have been able to resolve the path to the MTP (child) object. However the path resolver is acting on the in-progress transaction, whilst the data structure is only updated after the transaction completes (it is very hard to wind back the data structure in the case of aborting the transaction). Consequently the assumption is incorrect and the assert fires.
Being unable to add both parent and child object using a single USP Add message is a specific limitation in OBUSPA's Controller MTP implementation, rather than a limitation of OBUSPA in general. For example you can add a BulkData.Profile (parent) and Profile.Parameter (child) using a single USP Add message.
The crash should definitely be fixed. However the limitation may remain as I think it will be a lot of effort to make the data structure reflect the in-progress transaction and I'm not convinced that the effort is justified for this single case.

**Comment by holme-r** [comment]
Closing as issue has been addressed in 24th January 2022 commit.
