### ISSUE TITLE
Problem when deleting a CoAP connection

### ISSUE THREAD

**Issue by phlnd** [BroadbandForum/obuspa#42]
Hi team,

I noticed a problem when using the coap protocol.
When performing the test https://usp-test.broadband-forum.org/02-index-messages-and-path-names.html#sec:removal-of-subscriptions-that-have-no-associated-controller, 
when the connection to the second controller is removed, the connection to the first controller is no longer functional.

**Comment by holme-r** [comment]
Thanks for reporting the issue, I have been able to reproduce it.
The problem seems to be related to the fact that the test creates the second listening socket on the same port address as the first (Device.LocalAgent.MTP.2.CoAP.Port == Device.LocalAgent.MTP.1.CoAP.Port), then closes the second listening socket. I would not expect this to cause problems (as they are two separate sockets), but it does seem to.
As CoAP has now been deprecated by the USP 1.2 Specification, and because this is an edge case which is easily avoided (only have one CoAP listener per port), further investigation of the issue is low priority work.
