### ISSUE TITLE
Multi Instance Object - Refresh the live values on the Get Message

### ISSUE THREAD

**Issue by shanthakumarks** [BroadbandForum/obuspa#60]
Hi,

We are working on implementing the vendor code for multi instance datamodel objects. On each multi instance object code, we have implemented a load function that populates all the values of the parameters in a global structure and also calls DATA_MODEL_InformInstance() to create instances for that particular multi instance object. This load function is called by VENDOR_Start() function to load all the values in global structure during USP Agent boot time similar to device_security.c implementation in the core code.  All the registered GetParameterValue callback functions for each parameters get the value from the global structure when a Get message is received.

The limitation of this implementation is that it is loading the global structure only once when USP Agent boots up and hence the live values are not being updated. We want the multi instance object to be updated with live values on every time Get message is received. The only way we can do this is by calling the load function again when a Get message is received by the USP Agent.  Can we make use of USP_REGISTER_Object_RefreshInstances API for refreshing all the values of the parameters in the object by passing the load function as callback function ?  Appreciate your suggestion on this implementation.  It will be great if you can share any  document or example for such scenarios ?

Thanks.

**Comment by holme-r** [comment]
Yes, you can use the refresh instances callback function to load the parameter values into your global structure, and this is often a good paradigm.
The QUICK_START_GUIDE has an example of using the refresh instances callback (RefreshIPInterfaceInstances function), but it doesn't include calling any load function. Please be aware that the refresh instances callback function must call USP_DM_RefreshInstance, instead of USP_DM_InformInstance.
Also, when a refresh instances callback is registered, there is no need to explicitly call USP_DM_InformInstance at startup, as OBUSPA calls the refresh instances callback at startup automatically.
So I think you could just remove the call to your load function from VENDOR_Start(), then change your load function so that it calls USP_DM_RefreshInstance, instead of USP_DM_InformInstance, and register it as the refresh instances callback.

**Comment by shanthakumarks** [comment]
Thanks for the clarification. We were able to implement one tree of multi instance objects like Device.IP.Interface.{i}. , Device.IP.Interface.{i}.IPv4Address.{i}. and Device.IP.Interface.{i}.IPv6Address.{i}.  by having one common callback function like RefreshIPInterfaceInstances() as shown in the example provided in QUICK_START_GUIDE.md and it worked fine. 

If we decide to have different callback functions for each child object with different USP_REGISTER_Object_RefreshInstance() API then the child instances are not being populated.  For Example,  USP_REGISTER_Object_RefreshInstance("Device.IP.Interface.{i}.**IPv4Address**.{i}.", **RefreshIPv4Instances**) , USP_REGISTER_Object_RefreshInstance("Device.IP.Interface.{i}.**IPv6Address**.{i}.", **RefreshIPv6Instances**).  Is this a limitation ? or It is designed to work only with the top most parent multi-instance object with one common callback function ?

**Comment by holme-r** [comment]
It is designed to work with one common callback function for the top most parent multi-instance object and all of its child object instances. The thinking was that they are 'tied' together - you can't have Device.IP.Interface.1.IPv4Address.1, without first having Device.IP.Interface.1. Having separate callbacks would increase the chances of inconsistent instance numbers being registered for each level of the tree.
