### ISSUE TITLE
ScheduleTimer() Command fails

### ISSUE THREAD

**Issue by M0ulinamary** [BroadbandForum/obuspa#88]
Hi Team, 

I am testing commands supported by TR369. When i execute ScheduleTimer with below inputs, It is unable to find the "DelaySeconds" input, thrws error.

**Executable file contents:**
msg_id:"101" to_id:"proto::AgentA" stomp_agent_dest:"/queue/controller-notify-dest" stomp_instance:"1"
msg_type:"Operate" command:"Device.ScheduleTimer()" DelaySeconds":"60" command_key:"test63" send_resp:"true"

**Error on Agent:**
header {
  msg_id: "101"
  msg_type: OPERATE
}
body {
  request {
    operate {
      command: "Device.ScheduleTimer()"
      command_key: ""
      send_resp: false
    }
  }
}

OPERATE : processing at time 2023-05-31T08:13:07Z
**Start_ScheduleTimer: DelaySeconds argument not specified**

Could you please help me to know the missing argument ? Please help me to know how to specify the input argument for a command in a file while triggering to Agent from Controller ?

**Comment by holme-r** [comment]
It seems like the test controller is not populating the DelaySeconds argument in the Operate. Perhaps this is because you have speech marks at the end of DelaySeconds, when there shouldn't be any. In the test controller file try:
msg_type:"Operate" command:"Device.ScheduleTimer()" DelaySeconds:"60" command_key:"test63" send_resp:"true"

**Comment by holme-r** [comment]
Closing as there has been no comments for a while. Please re-open if there are any further comments.
